apiVersion: v1
kind: Template
metadata:
  name: phone-selector-template
  annotations:
    description: "Template for deploying Phone Selector Dash Application"
    tags: "python,dash,web-app"
    iconClass: "icon-python"
    openshift.io/display-name: "Phone Selector App"
parameters:
  - name: APP_NAME
    displayName: "Application Name"
    description: "The name assigned to all of the frontend objects defined in this template."
    value: "phone-selector"
    required: true
  - name: GIT_REPO
    displayName: "Git Repository URL"
    description: "The URL of the repository with your application source code."
    value: "https://github.com/giomara-larraga/researchers-night.git"
    required: true
  - name: GIT_REF
    displayName: "Git Reference"
    description: "Set this to a branch name, tag or other ref of your repository if you are not using the default branch."
    value: "master"
  - name: MEMORY_LIMIT
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    value: "512Mi"
    required: true
  - name: CPU_LIMIT
    displayName: "CPU Limit"
    description: "Maximum amount of CPU the container can use."
    value: "500m"
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      source:
        type: Git
        git:
          uri: ${GIT_REPO}
          ref: ${GIT_REF}
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              image: ${APP_NAME}:latest
              ports:
                - containerPort: 8050
              env:
                - name: PORT
                  value: "8050"
                - name: DEBUG
                  value: "false"
              resources:
                limits:
                  memory: ${MEMORY_LIMIT}
                  cpu: ${CPU_LIMIT}
                requests:
                  memory: 256Mi
                  cpu: 250m
              livenessProbe:
                httpGet:
                  path: /
                  port: 8050
                initialDelaySeconds: 30
                periodSeconds: 10
              readinessProbe:
                httpGet:
                  path: /
                  port: 8050
                initialDelaySeconds: 10
                periodSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      ports:
        - port: 8050
          targetPort: 8050
      selector:
        app: ${APP_NAME}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      to:
        kind: Service
        name: ${APP_NAME}
      port:
        targetPort: 8050
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
